/* Generated by AN DISI Unibo */ 
package it.unibo.pong

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Pong ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("	Sono il $name")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleEnemyHit",cond=whenDispatch("hit"))
				}	 
				state("handleEnemyHit") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("hit(NUM_GAME)"), Term.createTerm("hit(NUM_GAME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("	$name: recived ping ${payloadArg(0)}")
								if( (0..10).random() % 4 != 0  
								 ){CommUtils.outgreen("	$name: I hit the ball =)")
								forward("hit", "hit(39)" ,"ping" ) 
								}
								else
								 {CommUtils.outgreen("	$name: I miss the ball =(")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleEnemyHit",cond=whenDispatch("hit"))
				}	 
			}
		}
} 
