/* Generated by AN DISI Unibo */ 
package it.unibo.asyncclient

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Asyncclient ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("	Sono il $name")
						forward("fibo_dispatch", "fibo(46)" ,"server" ) 
						CommUtils.outcyan("	$name: asked for fibo of 46")
						forward("fibo_dispatch", "fibo(2)" ,"server" ) 
						CommUtils.outcyan("	$name: asked for fibo of 2")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="handle9",targetState="handle_dispatch",cond=whenDispatch("fibo_dispatch"))
				}	 
				state("handle_dispatch") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("fibo(X)"), Term.createTerm("fibo(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("	$name: recived dispatch ${payloadArg(0)}")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="handle10",targetState="handle_dispatch",cond=whenDispatch("fibo_dispatch"))
				}	 
			}
		}
} 
