/* Generated by AN DISI Unibo */ 
package it.unibo.led_usage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Led_usage ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("Sono la $name")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t10",targetState="handle_led",cond=whenDispatch("led_cmd"))
				}	 
				state("handle_led") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("manage_led(STARTSTOP)"), Term.createTerm("manage_led(STARTSTOP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name: recived manage_sonar ${payloadArg(0)}")
								if(  payloadArg(0) == "ON"  
								 ){CommUtils.outgreen("$name: ACCENDO")
								 Runtime.getRuntime().exec("python3 on.py")  
								}
								else
								 {CommUtils.outgreen("$name: SPENGO")
								  Runtime.getRuntime().exec("python3 off.py")  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="handle_led",cond=whenDispatch("led_cmd"))
				}	 
			}
		}
} 
