/* Generated by AN DISI Unibo */ 
package it.unibo.stazione

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Stazione ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var ledRed = false 	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("Sono la $name")
						delay(500) 
						request("manage_sonar", "manage_sonar(true)" ,"sonar" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t10",targetState="handle_sonar",cond=whenReply("manage_sonar"))
					transition(edgeName="t11",targetState="handle_led",cond=whenDispatch("manage_red_led"))
				}	 
				state("handle_led") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("accendi(N)"), Term.createTerm("accendi(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name: recived manage_red_led ${payloadArg(0)}")
								 ledRed = payloadArg(0).toBoolean()  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="handle_led",cond=whenDispatch("manage_red_led"))
				}	 
				state("handle_sonar") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="handle_led",cond=whenDispatch("manage_red_led"))
				}	 
			}
		}
} 
