/* Generated by AN DISI Unibo */ 
package it.unibo.pingobserver

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Pingobserver ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var Nlast = -1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("	Sono il $name")
						observeResource("localhost","8000","ctxpingpong","ping","update")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="recive_update6",targetState="handle_update",cond=whenDispatch("update"))
				}	 
				state("handle_update") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("update(STR,N)"), Term.createTerm("update(STR,N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Nlast = payloadArg(1).toInt()  
								CommUtils.outblue("$name: saw ${payloadArg(0)} with ${payloadArg(1)}")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="recive_update7",targetState="handle_update",cond=whenDispatch("update"))
					transition(edgeName="recive_update8",targetState="handle_test_req",cond=whenRequest("info_test"))
				}	 
				state("handle_test_req") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("info_test(X)"), Term.createTerm("info_test(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("info_test", "info_test", "obsinfo($Nlast)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
